"""Prepare and optionally publish the copied-repository staging smoke tree."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
# Subprocess is required for controlled git and Python argv without shell execution.
import subprocess  # nosec B404
import sys
import tempfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml

try:
    from scripts.repo_paths import find_repo_root
except ModuleNotFoundError:  # pragma: no cover - direct script execution
    from repo_paths import find_repo_root  # type: ignore[import-not-found,no-redef]


ROOT = find_repo_root(Path(__file__))
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import build_template  # noqa: E402
from scripts import template_contract  # noqa: E402


DEFAULT_OUTPUT = ROOT / "dist" / "staging-smoke"
DEFAULT_EVIDENCE = ROOT / "dist" / "staging-smoke-evidence.md"
DEFAULT_REMOTE = "https://github.com/reponomics/reponomics-dashboard-staging.git"
DEFAULT_EXPECTED_REPO = "reponomics/reponomics-dashboard-staging"
DEFAULT_BRANCH = "main"
DEFAULT_MESSAGE = "chore: publish staging smoke dashboard"
DEFAULT_REPOSITORIES = ("reponomics/reponomics-dashboard-action",)
SCENARIO_NAME = "public-encrypted-pages-no-readme"
STAGING_RECORD = Path(".reponomics/staging-smoke.json")
FULL_REPO_NAME_RE = re.compile(
    r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?/[A-Za-z0-9_.-]{1,100}$"
)


class StagingSmokeError(RuntimeError):
    """Raised when the staging smoke tree cannot be prepared or published."""


@dataclass(frozen=True)
class StagingSmokeResult:
    output_dir: Path
    evidence_file: Path
    published_commit: str | None
    record: dict[str, Any]


def _run(args: list[str], cwd: Path, *, env: dict[str, str] | None = None) -> None:
    # Every caller supplies a fixed git executable and an argument vector.
    subprocess.run(  # nosec B603
        args,
        cwd=cwd,
        env=env,
        check=True,
    )


def _output(args: list[str], cwd: Path) -> str:
    # Every caller supplies a fixed git executable and an argument vector.
    return subprocess.check_output(  # nosec B603
        args,
        cwd=cwd,
        text=True,
        stderr=subprocess.DEVNULL,
    ).strip()


def _git_value(*args: str) -> str:
    try:
        return _output(["git", *args], ROOT)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def _utc_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _split_repository_values(values: list[str]) -> list[str]:
    repositories: list[str] = []
    seen: set[str] = set()
    for value in values:
        for repository in re.split(r"[\s,]+", value.strip()):
            if not repository:
                continue
            if not FULL_REPO_NAME_RE.fullmatch(repository):
                raise StagingSmokeError(
                    "Staging repositories must be full GitHub names like "
                    + f"'owner/repo', got {repository!r}."
                )
            if repository not in seen:
                repositories.append(repository)
                seen.add(repository)
    return repositories


def resolve_repositories(
    repositories: list[str],
    publish_repositories: list[str],
) -> tuple[list[str], list[str]]:
    collect = _split_repository_values(repositories) or list(DEFAULT_REPOSITORIES)
    publish = _split_repository_values(publish_repositories) or list(collect)
    missing = sorted(set(publish) - set(collect))
    if missing:
        raise StagingSmokeError(
            "Publish repositories must be a subset of collect repositories: "
            + ", ".join(missing)
        )
    if len(publish) > 8:
        raise StagingSmokeError("The staging dashboard publish list must contain at most 8 repos.")
    return collect, publish


def _write_staging_config(
    output_dir: Path,
    *,
    collect_repositories: list[str],
    publish_repositories: list[str],
) -> None:
    config = {
        "i_have_read_the_readme": True,
        "data_mode": "encrypted",
        "publish_pages_dashboard": True,
        "publish_readme_dashboard": False,
        "artifact_retention_days": 90,
        "use_github_app": False,
        "auto_doctor_every_n_days": 0,
        "collect": {"repositories": collect_repositories},
        "publish": {"repositories": publish_repositories},
    }
    header = "\n".join(
        [
            "# Generated by scripts/staging_smoke.py for the copied-repository "
            + "staging smoke scenario.",
            "# This config intentionally exercises encrypted retained data, "
            + "GitHub Pages, and no README dashboard.",
        ]
    ) + "\n"
    (output_dir / "config.yaml").write_text(
        header + yaml.safe_dump(config, sort_keys=False),
        encoding="utf-8",
    )


def _read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def _validate_generated_config(output_dir: Path) -> dict[str, str]:
    env_file = output_dir / ".tmp-github-env"
    summary_file = output_dir / ".tmp-github-step-summary"
    env = {
        **os.environ,
        "GITHUB_ENV": str(env_file),
        "GITHUB_STEP_SUMMARY": str(summary_file),
        "GITHUB_REPOSITORY": DEFAULT_EXPECTED_REPO,
        "REPOSITORY_PRIVATE": "false",
    }
    # The current interpreter runs a fixed resolver path in the generated tree.
    result = subprocess.run(  # nosec B603
        [sys.executable, ".github/scripts/resolve-reponomics-config.py"],
        cwd=output_dir,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        for path in (env_file, summary_file):
            path.unlink(missing_ok=True)
        raise StagingSmokeError(
            "Generated staging config failed the copied-repository resolver:\n"
            + result.stderr.strip()
        )
    resolved = _read_env_file(env_file)
    for path in (env_file, summary_file):
        path.unlink(missing_ok=True)
    expected = {
        "REPONOMICS_SETUP_COMPLETE": "false",
        "DATA_MODE": "encrypted",
        "PUBLISH_PAGES_DASHBOARD": "true",
        "PUBLISH_README_DASHBOARD": "false",
        "USE_GITHUB_APP": "false",
        "COLLECTION_AUTH_MODE": "pat",
    }
    mismatches = {
        key: resolved.get(key)
        for key, value in expected.items()
        if resolved.get(key) != value
    }
    if mismatches:
        raise StagingSmokeError(f"Generated staging config resolved unexpectedly: {mismatches}")
    return resolved


def _build_record(
    *,
    output_dir: Path,
    remote: str,
    expected_repo: str,
    branch: str,
    collect_repositories: list[str],
    publish_repositories: list[str],
    resolved_config: dict[str, str],
) -> dict[str, Any]:
    contract = template_contract.load_contract()
    return {
        "schema_version": 1,
        "scenario": SCENARIO_NAME,
        "generated_at": _utc_now(),
        "source": {
            "repository": contract.action_repository,
            "commit": _git_value("rev-parse", "HEAD") or "unknown",
            "template_version": contract.template_version,
            "accepted_action": {
                "repository": contract.accepted_action.repository,
                "tag": contract.accepted_action.tag,
                "sha": contract.accepted_action.sha,
                "default_ref": contract.accepted_action.default_ref,
            },
        },
        "target": {
            "remote": remote,
            "expected_repo": expected_repo,
            "branch": branch,
        },
        "config": {
            "data_mode": "encrypted",
            "publish_pages_dashboard": True,
            "publish_readme_dashboard": False,
            "artifact_retention_days": 90,
            "use_github_app": False,
            "collection_auth_mode": "pat",
            "resolved": resolved_config,
        },
        "repositories": {
            "collect": collect_repositories,
            "publish": publish_repositories,
        },
        "operator_requirements": [
            "Target repository is public.",
            "GitHub Pages source is set to GitHub Actions.",
            "Repository secret COLLECTION_TOKEN is set to a low-scope token "
            + "that can read the selected public repositories.",
            "Repository secret DASHBOARD_SECRET_DO_NOT_REPLACE is set and retained.",
            "Run the generated Setup workflow before Collect and Publish.",
            "Unlock the deployed Pages dashboard in a browser with "
            + "DASHBOARD_SECRET_DO_NOT_REPLACE.",
        ],
        "output_dir": output_dir.as_posix(),
    }


def _write_record(output_dir: Path, record: dict[str, Any]) -> Path:
    path = output_dir / STAGING_RECORD
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _repo_slug(expected_repo: str) -> str:
    slug = expected_repo.removesuffix(".git").strip("/")
    return slug or DEFAULT_EXPECTED_REPO


def _write_evidence(
    path: Path,
    *,
    record: dict[str, Any],
    published_commit: str | None,
) -> None:
    target_repo = _repo_slug(str(record["target"]["expected_repo"]))
    branch = str(record["target"]["branch"])
    if "/" in target_repo:
        owner, repo = target_repo.split("/", 1)
        pages_url = f"https://{owner}.github.io/{repo}/"
    else:
        pages_url = "<staging Pages URL>"
    status = "published" if published_commit else "prepared dry run"
    commit_line = f"- Published commit: `{published_commit}`\n" if published_commit else ""
    repositories = "\n".join(
        f"- `{repository}`" for repository in record["repositories"]["collect"]
    )
    text = f"""# Reponomics Staging Smoke Evidence

- Status: {status}
- Scenario: `{record["scenario"]}`
- Generated at: `{record["generated_at"]}`
- Source commit: `{record["source"]["commit"]}`
- Template version: `{record["source"]["template_version"]}`
- Target: `{target_repo}` branch `{branch}`
{commit_line}
## Scenario

- Public copied dashboard repository
- `data_mode: encrypted`
- `publish_pages_dashboard: true`
- `publish_readme_dashboard: false`
- PAT-based `COLLECTION_TOKEN`

## Repositories

{repositories}

## Operator Checks

- Target repository visibility is public.
- GitHub Pages source is set to GitHub Actions.
- `COLLECTION_TOKEN` is set as a repository secret and can read the selected repositories.
- `DASHBOARD_SECRET_DO_NOT_REPLACE` is set as a repository secret and has not been replaced between runs.
- Generated Setup workflow has completed successfully.
- Generated Collect and Publish workflow has completed successfully at least twice.
- Pages deployment succeeded.
- `{pages_url}` unlocks in a browser with `DASHBOARD_SECRET_DO_NOT_REPLACE`.
- Dashboard renders the expected navigation and repository views.

## Workflow Commands

```bash
gh workflow run setup.yml --repo {target_repo} --ref {branch}
gh workflow run collect-and-publish.yml --repo {target_repo} --ref {branch} -f skip_collect=false
gh workflow run collect-and-publish.yml --repo {target_repo} --ref {branch} -f skip_collect=false
```
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _remote_url(remote: str) -> str:
    try:
        # git is fixed; the remote is a distinct argument and is repository-checked before use.
        return subprocess.check_output(  # nosec B603, B607
            ["git", "remote", "get-url", remote],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError as exc:
        if "/" in _remote_repo_path(remote):
            return remote
        raise StagingSmokeError(f"Unknown git remote or repository URL: {remote}") from exc


def _remote_repo_path(remote_url: str) -> str:
    parsed = urlparse(remote_url)
    if parsed.scheme:
        path = parsed.path
    elif ":" in remote_url and not remote_url.startswith("/"):
        path = remote_url.split(":", 1)[1]
    else:
        path = remote_url
    path = path.strip().rstrip("/")
    if path.endswith(".git"):
        path = path[:-4]
    parts = [part for part in path.split("/") if part]
    if len(parts) >= 2:
        return "/".join(parts[-2:])
    return parts[-1] if parts else ""


def _display_remote_url(remote_url: str) -> str:
    parsed = urlparse(remote_url)
    if parsed.scheme and parsed.hostname and "@" in parsed.netloc:
        host = parsed.hostname
        if parsed.port is not None:
            host = f"{host}:{parsed.port}"
        return parsed._replace(netloc=host).geturl()
    return remote_url


def _assert_expected_repo(remote_url: str, expected_repo: str) -> None:
    actual = _remote_repo_path(remote_url)
    expected = expected_repo.removesuffix(".git").strip("/")
    if "/" in expected:
        matched = actual == expected
    else:
        matched = actual == expected or actual.endswith(f"/{expected}")
    if not matched:
        raise StagingSmokeError(
            f"Remote safety check failed: expected {expected_repo}, got {actual or remote_url}"
        )


def _replace_worktree_contents(worktree: Path, output_dir: Path) -> None:
    for child in worktree.iterdir():
        if child.name == ".git":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()
    for child in output_dir.iterdir():
        target = worktree / child.name
        if child.is_dir():
            shutil.copytree(child, target)
        else:
            shutil.copy2(child, target)


def _has_staged_changes(worktree: Path) -> bool:
    # git is the fixed executable and this command has no dynamic arguments.
    result = subprocess.run(  # nosec B603, B607
        ["git", "diff", "--cached", "--quiet"],
        cwd=worktree,
        check=False,
    )
    if result.returncode == 0:
        return False
    if result.returncode == 1:
        return True
    result.check_returncode()
    return False


def publish_staging_tree(
    output_dir: Path,
    *,
    remote: str,
    branch: str,
    message: str,
    expected_repo: str,
    push: bool,
) -> str | None:
    output_dir = output_dir.resolve()
    if not output_dir.exists():
        raise StagingSmokeError(f"Staging smoke output does not exist: {output_dir}")
    if not (output_dir / "config.yaml").is_file():
        raise StagingSmokeError("Staging smoke output is missing config.yaml")
    if not (output_dir / STAGING_RECORD).is_file():
        raise StagingSmokeError(f"Staging smoke output is missing {STAGING_RECORD}")

    remote_url = _remote_url(remote)
    _assert_expected_repo(remote_url, expected_repo)
    display_remote_url = _display_remote_url(remote_url)
    print(f"Prepared staging smoke tree at {output_dir}")
    print(f"Target: {display_remote_url} {branch}")
    if not push:
        print("Dry run only. Re-run with --push to replace the staging branch.")
        return None

    with tempfile.TemporaryDirectory(prefix="staging-smoke-repo-") as tmp:
        worktree = Path(tmp) / "repo"
        worktree.mkdir()
        _run(["git", "init", "-b", branch], worktree)
        _run(["git", "config", "user.name", "reponomics-staging[bot]"], worktree)
        _run(
            [
                "git",
                "config",
                "user.email",
                "286571062+reponomics-dashboard[bot]@users.noreply.github.com",
            ],
            worktree,
        )
        _run(["git", "remote", "add", "target", remote_url], worktree)

        remote_ref = f"refs/heads/{branch}"
        remote_oid = _output(["git", "ls-remote", "--heads", "target", branch], worktree)
        if remote_oid:
            expected_oid = remote_oid.split()[0]
            _run(["git", "fetch", "target", remote_ref], worktree)
            _run(["git", "checkout", "-B", branch, "FETCH_HEAD"], worktree)
            lease = f"--force-with-lease={remote_ref}:{expected_oid}"
        else:
            _run(["git", "checkout", "--orphan", branch], worktree)
            lease = f"--force-with-lease={remote_ref}:"

        _replace_worktree_contents(worktree, output_dir)
        _run(["git", "add", "-A"], worktree)
        if _has_staged_changes(worktree):
            _run(
                ["git", "-c", "core.hooksPath=/dev/null", "commit", "-m", message],
                worktree,
            )
        else:
            print(f"Staging smoke tree already matches target {branch}.")
        published_commit = _output(["git", "rev-parse", "HEAD"], worktree)
        _run(["git", "push", lease, "target", f"HEAD:{remote_ref}"], worktree)

    verified = _output(["git", "ls-remote", "--heads", remote_url, branch], ROOT)
    verified_commit = verified.split()[0] if verified else ""
    if verified_commit != published_commit:
        raise StagingSmokeError(
            f"Published branch verification failed: expected {published_commit}, "
            + f"got {verified_commit or 'missing'}"
        )
    print(f"Published staging smoke tree to {display_remote_url}/{branch}")
    print(f"Published commit: {published_commit}")
    return published_commit


def prepare_staging_smoke(
    *,
    output_dir: Path,
    remote: str,
    expected_repo: str,
    branch: str,
    message: str,
    repositories: list[str],
    publish_repositories: list[str],
    evidence_file: Path,
    push: bool,
) -> StagingSmokeResult:
    collect, publish = resolve_repositories(repositories, publish_repositories)
    output_dir = output_dir.resolve()
    build_template.build_template(output_dir)
    _write_staging_config(
        output_dir,
        collect_repositories=collect,
        publish_repositories=publish,
    )
    resolved_config = _validate_generated_config(output_dir)
    record = _build_record(
        output_dir=output_dir,
        remote=remote,
        expected_repo=expected_repo,
        branch=branch,
        collect_repositories=collect,
        publish_repositories=publish,
        resolved_config=resolved_config,
    )
    _write_record(output_dir, record)
    published_commit = publish_staging_tree(
        output_dir,
        remote=remote,
        branch=branch,
        message=message,
        expected_repo=expected_repo,
        push=push,
    )
    _write_evidence(evidence_file, record=record, published_commit=published_commit)
    print(f"Wrote staging smoke evidence: {evidence_file}")
    return StagingSmokeResult(
        output_dir=output_dir,
        evidence_file=evidence_file,
        published_commit=published_commit,
        record=record,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--remote", default=DEFAULT_REMOTE)
    parser.add_argument("--expected-repo", default=DEFAULT_EXPECTED_REPO)
    parser.add_argument("--branch", default=DEFAULT_BRANCH)
    parser.add_argument("--message", default=DEFAULT_MESSAGE)
    parser.add_argument("--repository", action="append", default=[])
    parser.add_argument("--publish-repository", action="append", default=[])
    parser.add_argument("--evidence", type=Path, default=DEFAULT_EVIDENCE)
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()
    prepare_staging_smoke(
        output_dir=args.output,
        remote=args.remote,
        expected_repo=args.expected_repo,
        branch=args.branch,
        message=args.message,
        repositories=args.repository,
        publish_repositories=args.publish_repository,
        evidence_file=args.evidence,
        push=args.push,
    )


if __name__ == "__main__":
    try:
        main()
    except StagingSmokeError as exc:
        print(f"Staging smoke error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
