"""Render a README that intentionally contains no traffic metrics."""

import html
import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path


OUTPUT_PATH = Path("README.md")
ASSET_DIR = Path("docs") / "assets"
UPDATE_NOTICE_ENV = "REPONOMICS_UPDATE_NOTICE_JSON"


def _pages_line(pages_dashboard: str) -> str:
    repo = os.environ.get("GITHUB_REPOSITORY", "OWNER/REPO")
    owner, _, name = repo.partition("/")
    if pages_dashboard == "encrypted":
        return (
            f"Encrypted dashboard: `https://{owner}.github.io/{name}/` "
            "(requires your dashboard key)"
        )
    return "Pages dashboard: disabled"


def _load_update_notice():
    raw = os.environ.get(UPDATE_NOTICE_ENV, "")
    if not raw:
        return None
    try:
        notice = json.loads(raw)
    except json.JSONDecodeError:
        return None
    if not isinstance(notice, dict):
        return None
    version = str(notice.get("version") or "").strip()
    title = str(notice.get("title") or "").strip()
    url = str(notice.get("url") or "").strip()
    summary = str(notice.get("summary") or "").strip()
    if not version or not title or not url:
        return None
    return {"version": version, "title": title, "url": url, "summary": summary}


def _update_notice_lines():
    notice = _load_update_notice()
    if not notice:
        return []
    summary = f" {html.escape(notice['summary'])}" if notice["summary"] else ""
    return [
        "<sub>"
        f"<strong>{html.escape(notice['title'])}</strong>"
        f"{summary} "
        f"<a href=\"{html.escape(notice['url'], quote=True)}\">"
        f"View {html.escape(notice['version'])}</a>."
        "</sub>",
        "",
    ]


def render() -> None:
    pages_dashboard = os.environ.get("PAGES_DASHBOARD", "encrypted")
    artifact_mode = os.environ.get("ARTIFACT_SECURITY_MODE", "plain")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    shutil.rmtree(ASSET_DIR, ignore_errors=True)

    lines = [
        "# GitHub Traffic Report",
        "",
        "[![Collect GitHub Traffic](../../actions/workflows/collect.yml/badge.svg)]"
        "(../../actions/workflows/collect.yml)",
        "",
        f"<sub>Last collection: {now}</sub>",
        "",
        "Traffic collection is active, but this README is configured not to "
        "publish traffic metrics.",
        "",
        "- README analytics summary: disabled",
        f"- {_pages_line(pages_dashboard)}",
        f"- Actions data artifact: {artifact_mode}",
        "",
        "Setup and privacy details are in [docs/README.md](docs/README.md).",
        "",
        "---",
        "",
    ]
    lines.extend(_update_notice_lines())
    lines.extend([
        "<sub>Generated by "
        "[GitHub Traffic Report Template]"
        "(https://github.com/hesreallyhim/github-traffic-report-template)"
        "</sub>",
        "",
    ])
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print("README.md updated without traffic metrics.")


if __name__ == "__main__":
    render()
