name: OSV SARIF scan

on:
  push:
    branches: [main]
  schedule:
    - cron: "7 10 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    name: OSV scanner
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run scanner
        id: scan
        uses: google/osv-scanner-action/osv-scanner-action@fa4ff678dd5d0a4fa3d628e57af8162873e93cd6 # v2.3.8
        with:
          scan-args: |-
            --output=results.json
            --format=json
            --recursive
            ./
        continue-on-error: true

      - name: Generate SARIF
        uses: google/osv-scanner-action/osv-reporter-action@a82132c0bd6c7261ffcb78e754c46c70ab57ad9a # v2.3.8
        with:
          scan-args: |-
            --output=osv-scanner.sarif
            --new=results.json
            --gh-annotations=false
            --fail-on-vuln=true

      - name: Upload SARIF artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: OSV Scanner SARIF file
          path: osv-scanner.sarif
          retention-days: 5

      - name: Upload SARIF to code scanning
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          sarif_file: osv-scanner.sarif

      - name: Print Code Scanning URL
        if: ${{ !cancelled() }}
        run: |
          echo "View the OSV-Scanner results in the Security tab:"
          echo "${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=is%3Aopen+branch%3A${GITHUB_REF_NAME}+tool%3Aosv-scanner"
